# Generated by Django 4.2.5 on 2023-09-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='timestamp',
        ),
    ]
