# Generated by Django 4.2.5 on 2023-09-30 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_video_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video_file', models.FileField(blank=True, upload_to='videos/')),
                ('is_complete', models.BooleanField(default=False)),
                ('video_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
